### ISSUE TITLE
Support FreeRADIUS 3 in redundancy setup

### ISSUE THREAD

**Issue by plettich** [NetKnights-GmbH/privacyidea-appliance#89]
FreeRADIUS 3 is already supported in the appliance (#66 ), but when setting up redundancy, it still tries to access the old configuration files/directories.

**Comment by cornelinux** [comment]
Should we add this to milestone 3.1?

**Comment by plettich** [comment]
Sure, i'll check if we can use some generic detection of the freeRADIUS version.

**Comment by plettich** [comment]
Ok, that MS is already due... It might take a little to test all the occurrences.

**Comment by cornelinux** [comment]
> Sure, i'll check if we can use some generic detection of the freeRADIUS version.

Or should we simply sync both possible directories for freeradius2 **and** freeradius3?

**Comment by cornelinux** [comment]
On Ubuntu 18.04 3.1~dev3 fails to copy freeradius:


~~~~
Traceback (most recent call last):
  File "/usr/bin/pi-appliance", line 23, in <module>
    main()
  File "/opt/pi-appliance/lib/python3.6/site-packages/authappliance/menu.py", line 2122, in main
    pS.main_menu()
  File "/opt/pi-appliance/lib/python3.6/site-packages/authappliance/menu.py", line 1888, in main_menu
    menu()
  File "/opt/pi-appliance/lib/python3.6/site-packages/authappliance/menu.py", line 812, in menu
    menu()
  File "/opt/pi-appliance/lib/python3.6/site-packages/authappliance/menu.py", line 908, in setup_redundancy
    self.peer.setup_freeradius()
  File "/opt/pi-appliance/lib/python3.6/site-packages/authappliance/menu.py", line 547, in setup_freeradius
    for filename in os.listdir(directory):
FileNotFoundError: [Errno 2] No such file or directory: '/etc/freeradius/modules'
~~~~
