### ISSUE TITLE
Import webserver certifcate

### ISSUE THREAD

**Issue by pablo-knight** [NetKnights-GmbH/privacyidea-appliance#98]
Import webserver certificate fails

~~~~python
Traceback (most recent call last):
  File "/usr/bin/pi-appliance", line 23, in <module>
    main()
  File "/opt/pi-appliance/lib/python3.8/site-packages/authappliance/menu.py", line 2150, in main
    pS.main_menu()
  File "/opt/pi-appliance/lib/python3.8/site-packages/authappliance/menu.py", line 1916, in main_menu
    menu()
  File "/opt/pi-appliance/lib/python3.8/site-packages/authappliance/menu.py", line 130, in menu
    menu()
  File "/opt/pi-appliance/lib/python3.8/site-packages/authappliance/menu.py", line 180, in import_certificate
    files = self.apache.get_imports(homedir)
  File "/opt/pi-appliance/lib/python3.8/site-packages/authappliance/lib/appliance.py", line 613, in get_imports
    f = f.decode("ascii")
AttributeError: 'str' object has no attribute 'decode'
~~~~

**Comment by cornelinux** [comment]
Looks like a usual unicode/encoding issue to me.
